[package]
edition = "2021"
name = "osmosis-std"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmos-sdk-proto = {version = "0.12.3", default-features = false}
prost = "0.10.4"
prost-types = "0.10.1"
