[package]
name = "abstract-osmosis-dex-adapter"
version = "0.15.2"
authors = ["Abstract Money <contact@abstract.money>"]
edition = "2021"
description = "Abstract DexCommand implementation for Osmosis"
license = "MIT OR Apache-2.0"

[dependencies]
cw20 = { verion="0.15" }
cosmwasm-std = {version = "1.1.2", features = ["stargate"]}

osmosis-std = {path="../osmosis-std/"}

#Abstract dependencies 
abstract-core = { git="https://github.com/AbstractSDK/contracts" }
abstract-sdk = { git="https://github.com/AbstractSDK/contracts" }
abstract-adapter-utils =  {git="https://github.com/AbstractSDK/adapters", branch="feature/impl-in-origin-repo"}
abstract-dex-adapter-traits = {git="https://github.com/AbstractSDK/adapters", branch="feature/impl-in-origin-repo"}
cw-asset = "3.0.0"
