[package]
description = "CosmWasm integration testing for Osmosis"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "osmosis-testing"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
cosmrs = {version = "0.7", features = ["cosmwasm"]}
cosmwasm-std = "1.0.0"
osmosis-std = {version = "0.1.5", path = "../osmosis-std"}
prost = "0.10"
serde = "1.0.144"
serde_json = "1.0.85"
thiserror = "1.0.34"

[build-dependencies]
bindgen = "0.60.1"

[dev-dependencies]
cw1-whitelist = "0.14.0"
rayon = "1.5.3"
