name: schedule check
on:
  workflow_dispatch:
    name: manual trigger

  schedule:
    - cron: "5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone Osmosis repo
        run: |
          git clone https://github.com/osmosis/osmosis.git

      - run: |
          ls
          ./scripts/check-updates.sh
