name: update and rebuild [main]
on:
  workflow_dispatch:
    name: manula trigger
  schedule:
    - cron: "5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run update-and-rebuild
        uses: osmosis/osmosis-rust/.github/workflows/update-and-rebuild.yaml@main
        with:
          osmosis_rev: main
