name: schedule check
on:
  workflow_dispatch:
    name: manual trigger

  schedule:
    - cron: "5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          git submodule update --init --recursive
          cd dependencies/osmosis
          git branch -r --format="%(refname:short) %(objectname)" --list origin/main
