on:
  workflow_dispatch:
    name: update and rebuild
    inputs:
      version:
        description: "Osmosis version"
        required: true
        type: choice
        options:
          - main
          - v13
          - v14
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "version: $VERSION"
        env:
          VERSION: ${{ inputs.version }}
